### ISSUE TITLE
Allow users to define custom controllers

### ISSUE THREAD

**Issue by m-abdulhak** [m-abdulhak/SwarmJS#5]
Add a code editor that allows users to dynamically define and use their own controllers for the specified scene from the UI without the need to modify the code and redeploy.

**Comment by avardy** [comment]
Sorry I'm a month late in taking a look at this.  Overall, it seems to work great once a scene is loaded.  However, there are some outstanding issues:

1. When switching between scenes, the "loop" field will update once the user clicks the "Reset Code" button.  However, the "init" field doesn't.
2. In the Orbital Construction scene the "loop" field for the default code calls another function (getAngularSpeed).  This doesn't show up anywhere.  Perhaps we just need to forbid either block of code from calling external functions?
